### ISSUE TITLE
v4 SSR gives incorrect urls

### ISSUE THREAD

**Issue by osenvosem** [ReactTraining/react-router#4523]
## Version
4.0.0-beta.5

## Expected Behavior
I expect it to render correct urls. 🙂

## Actual Behavior
Renders `a` tags with incorrect url.

## Steps to reproduce

![screen shot 2017-02-13 at 18 34 09](https://cloud.githubusercontent.com/assets/6762673/22889782/5eef55fc-f21b-11e6-9f81-3acbdda82d9e.png)

If I disable Javascript in browser and the app renders only on the server, incorrect urls render with double slashes.

```javascript
<Link to="/">Home</Link> // url renders as '//'
<Link to="/one">One</Link> // renders as '//one'
// etc...
```

### Server side code

```javascript
  const renderLayout = (html, state = {}) => {
    return `
      <!DOCTYPE html>
      <html lang="en">
      <head>
        <meta charset="UTF-8">
        <title>My lovely app</title>
      </head>
      <body>
        <div id="root"><div>${html}</div></div>

        <script>window.__INITIAL_STATE__ = ${JSON.stringify(state)}</script>
        <script src="/assets/manifest.bundle.js"></script>
        <script src="/assets/vendor.bundle.js"></script>
        <script src="/assets/main.bundle.js"></script>
      </body>
      </html>
    `
  }

  app.use('*', (req, res) => {
    const context = {}
    const renderedLayout = renderLayout(
      renderToString(
        <StaticRouter location={req.url} context={context}>
          <Root />
        </StaticRouter>
      ), {}
    )

    if (context.url) {
      return res.redirect(302, context.url)
    } else {
      return res.send(renderedLayout)
    }
  }) 

```

**Comment by pshrmn** [comment]
Fixed in #4484

**Comment by osenvosem** [comment]
@pshrmn sorry for maybe a silly question, but how can I install fixed version? The `'4.0.0-beta.5'` version I'm currently using is the latest one in `react-router` and `react-router-dom`.

**Comment by pshrmn** [comment]
There isn't a good answer to that. Until a new release is put out so that it can be installed through `npm`, the most correct solution would be to clone the repo, build the v4 branch, and `npm link` it. That is a lot of work for something with a simple fix. The hot-fix solution would be to find `node_modules/react-router/StaticRouter.js` and modify line `105` (hopefully that is the correct number) to be:

```js
return (0, _PathUtils.addLeadingSlash)(_this.props.basename + createURL(path));
```

That moves the closing parentheses for the `addLeadingSlash` function, which is the fix.

That isn't ideal, but it will prevent your code from generating the extra slash until the fix is released.

**Comment by sponia-joker** [comment]
I aslo encountered then problem,thanks solved problem

**Comment by sponia-joker** [comment]
when the value is 'javascript:;',the problem is still exist.
 (client) "cursor-hand" href="javascript:;" data-r
 (server) "cursor-hand" href="/javascript:;" data-
Is there a better solution here?
thanks
