### ISSUE TITLE
React-router intercepting server routes

### ISSUE THREAD

**Issue by g-golden** [ReactTraining/react-router#5520]
## Version
4.2.2

## Steps to reproduce
Have a server that has an endpoint to be directly navigated to (e.g. /api/logout):

```
app.get('/api/logout', (req, res) => {
  req.logout();
  res.redirect('/');
});

if (process.env.NODE_ENV === 'production') {
  app.use(express.static('client/build'));

  const path = require('path');
  app.get('*', (req, res) => {
    res.sendFile(path.resolve(__dirname, 'client', 'build', 'index.html'));
  })
}
```

Add navigation in the react app like \<a href="/api/logout"> or window.location = '/api/logout'

## Expected Behavior
A page refresh to the same domain through \<a> tag navigation or setting window.location should go through server routing before loading the react app.

## Actual Behavior
The correct route request isn't made to the server and the route is treated as a react-route. 

This behavior is only experienced in a production environment. However, there is a strange case where everything works as intended. In firefox private browsing, routing works correctly. In regular firefox, regular chrome, and incognito chrome, routing is not working, as described above.

**Comment by timdorr** [comment]
This isn't a React Router issue. This is an express issue.

**Comment by g-golden** [comment]
The same issue occurs when using nginx to serve the react files

**Comment by pshrmn** [comment]
Neither setting `window.location` nor using an anchor will be intercepted by React Router. Both of those will make requests to the server. You then have to configure your server to catch `/api` calls before the catch all handler.

The only reason that React Router could cause an issue here is if you're using a `<Link>`. If you are, you need to switch to an `<a>`.

**Comment by g-golden** [comment]
@pshrmn I am using `<a>` not `<Link>`. I am also using `window.location`. Both seem to be getting intercepted by react router. Using anchor and window.location to navigate to /api clearly makes the page refresh but the server isn't catching it and serves the catch all handler. 

When testing with express, my `/api` definition is above the catch all as shown in the original post. I also tested with nginx and put the `/api` definition above the catch all (even though the stackoverflow post I linked above shows the other way).

**Comment by g-golden** [comment]
@pshrmn @timdorr I fixed things by removing the registerServiceWorker() from the create-react-app boilerplate.

**Comment by LinkCable** [comment]
@g-golden can you go into some detail into your fix? I'm encountering the same issue, but deleting the service worker hasn't fixed it.

**Comment by g-golden** [comment]
@LinkCable All I did was comment out the one line at the end of index.js, in the create-react-app boilerplate:
`// registerServiceWorker();`
Also, you might have to clear cache/cookies in your browser for the change to take effect.

**Comment by LinkCable** [comment]
@g-golden dang, I tried that and nothing happened. I cleared the cache and even my cloudflare cache, but was still getting the weird error of working in Firefox but not in Chrome. Perhaps it's because I'm trying to serve up a file instead of a route?

**Comment by g-golden** [comment]
Perhaps, but I think it still sounds like the same issue. Strange behavior. Sorry I can't help more.

**Comment by mostafa69d** [comment]
I had the same issue and after trying everything on this planet I found some discussions (here)[https://github.com/facebook/create-react-app/issues/1910].
As I mentioned in my comment in the post removing the registerServiceWorker and using unregister() in my index.js solved my problem. Now my index.js looks like this:
```
const composeEnhancers = window.__REDUX_DEVTOOLS_EXTENSION_COMPOSE__ || compose;
const store = createStore(reducers,{},composeEnhancers(applyMiddleware(reduxThunk)));

store.dispatch({type:AUTH,auth:isUserAuthorized()});

unregister();

ReactDOM.render(

    <Provider store={store}> 

        <App/>

    </Provider> , 

     document.getElementById('root'));

```
@LinkCable Make sure to use unregister() if you had previously enabled the service.( and for sure clear cache and hard reload' on your browser.
 If you had previously enabled service workers in your production deployment and have decided that you would like to disable them for all your existing users, you can swap out the call to registerServiceWorker() in src/index.js first by modifying the service worker import:

> If you had previously enabled service workers in your production deployment and have decided that you would like to disable them for all your existing users, you can swap out the call to registerServiceWorker() in src/index.js first by modifying the service worker import:
> 
>` import { unregister } from './registerServiceWorker';`
> and then call unregister() instead. After the user visits a page that has unregister(), the service worker will be uninstalled. Note that depending on how /service-worker.js is served, it may take up to 24 hours for the cache to be invalidated.
you can read more [here](https://github.com/facebook/create-react-app/blob/master/packages/react-scripts/template/README.md#opting-out-of-caching)

**Comment by LinkCable** [comment]
@mostafa69d Thanks! I just updated to the latest create-react-app release as they took out the service worker by default after seeing all the issues it caused.

**Comment by jonatanrinckus** [comment]
Removed registerServiceWorker and unregister fix this issue, what this registerServiceWorker do to fuck everything?
